services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      args:
        RUBY_VERSION: 3.1.1
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: docker
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
