title: SaaS Starter Docs
email: hello@saas-starter.app
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title/
search_enabled: false
nav_external_links:
  - title: Changelog
    url: https://github.com/jshawl/saas-starter/blob/ma/CHANGELOG.md
  - title: SaaS Starter on GitHub
    url: https://github.com/jshawl/saas-starter
aux_links:
  "Sign Up":
    - "https://saas-starter.app"
  "SaaS Starter on GitHub":
    - "https://github.com/jshawl/saas-starter"
callouts:
  note:
    title: Note
    color: purple

theme: just-the-docs
plugins:
  - jekyll-feed

compress_html:
  ignore:
    envs: all
